### PR TITLE
css-brochure-form complete

### PR DESCRIPTION
**Pull request by luiderek**
image

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Almost there, just a couple minor differences in the select.
- The text content, relative to the size of the select, should be smaller.
- The spacing around the text content should match.
- Your background has a slight purple tinge instead of being neutral grey.


---

image

---

image

**Comment by TimelikeClosure** [comment]
@luiderek Can you add a new screenshot of what the page looks like now?

**Comment by luiderek** [comment]
image

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Please adjust the relative sizes of the labels vs the inputs / select so they're the same as the example:

---



---

image

**Comment by luiderek** [comment]
image

**Review by TimelikeClosure — APPROVED** [review]

**Pull request merged**
